version: '3'
services:
  frontend:
    build:
      context: ./frontend/electrust
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/electrust-api
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend