name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
      working-directory: ./backend/electrust-api

    # - name: Build and Test
    #   run: npm test
    #   working-directory: ./backend/electrust-api

    - name: Deploy Backend
      run: |
        npm run dev
      working-directory: ./backend/electrust-api